name: rss-lambda
services:
  rss-lambda:
    image: ghcr.io/sekai-soft/rss-lambda:latest
    container_name: rss-lambda
    restart: unless-stopped
    env_file:
      - env
    network_mode: service:rss-lambda-ts
  rss-lambda-ts:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: rss-lambda
    environment:
      - TS_EXTRA_ARGS=--advertise-tags=tag:server
      - TS_STATE_DIR=/var/lib/tailscale
    env_file:
      - /home/nixos/env-tailscale
    volumes:
      - rss-lambda-ts:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  rss-lambda-ts:
