services:
  tensorflow-serving:
    image: bitnami/tensorflow-serving:latest
    ports:
      - "8501:8501"
    volumes:
      - ./blobs/yolov3:/bitnami/model-data
    environment:
      - TENSORFLOW_SERVING_MODEL_NAME=yolov3
